name = "Tempotrons"
uuid = "c1564fa2-8b04-11e9-286d-9bb0cabf4b0e"
authors = ["Aviv Dotan <avivdot@post.bgu.ac.il>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"

[compat]
julia = "≥ 1.1.0"

[extras]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"

[targets]
test = ["PyCall", "PyPlot"]
